# -*- coding: utf-8 -*-
"""Exploratory Data Analysis with Python for Beginner.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UmeDrtb7X4_6MHLr1mOG6uOEMi0Py1oo

# Memanggil library di Python
"""

import numpy as np
import pandas as pd

"""# Membaca file dari Excel atau CSV sebagai data frame
# Tugas Praktek
"""

import pandas as pd
order_df = pd.read_csv("https://storage.googleapis.com/dqlab-dataset/order.csv")

"""# Melihat struktur kolom dan baris dari data frame
# Tugas Praktek
"""

import pandas as pd
order_df = pd.read_csv("https://storage.googleapis.com/dqlab-dataset/order.csv")
print(order_df.shape)

"""# Melihat preview data dari data frame
# Tugas Praktek
"""

import pandas as pd
order_df = pd.read_csv("https://storage.googleapis.com/dqlab-dataset/order.csv")
print(order_df.head(10))

"""# Statistik Deskriptif dari Data Frame - Part 1"""

print(order_df.describe())

# Menampilkan semua kolom termasuk kolom bertipe category
print(order_df.describe(include="all"))

"""# Statistik Deskriptif dari Data Frame - Part 2"""

print(order_df.describe(include=["object"]))

"""# Statistik Deskriptif dari Data Frame - Part 3"""

print(order_df.loc[:, "quantity"].mean())

print(order_df.loc[:, "quantity"].median())

print(order_df.loc[:, "quantity"].mode()[0])

"""# Tugas Praktek"""

import pandas as pd
order_df = pd.read_csv("https://storage.googleapis.com/dqlab-dataset/order.csv")

# Quick summary  dari segi kuantitas, harga, freight value, dan weight
print(order_df.describe())

# Median median dari total pembelian konsumen per transaksi kolom price
print(order_df.loc[:, "price"].median())

"""# Mengenal dan Membuat Distribusi Data dengan Histogram
# Tugas Praktek
"""

import pandas as pd
import matplotlib.pyplot as plt
order_df = pd.read_csv("https://storage.googleapis.com/dqlab-dataset/order.csv")

# Plot histogram kolom: price
order_df[["price"]].plot.hist(figsize=(4, 5), bins=10, xlabelsize=8, ylabelsize=8)

# Untuk menampilkan histogram plot
plt.show()

"""# Standar Deviasi dan Varians pada Pandas
# Tugas Praktek
"""

import pandas as pd
import matplotlib.pyplot as plt
order_df = pd.read_csv("https://storage.googleapis.com/dqlab-dataset/order.csv")

# Standar variasi kolom product_weight_gram
order_df.loc[:, "product_weight_gram"].std()

# Varians kolom product_weight_gram
order_df.loc[:, "product_weight_gram"].var()

"""# Menemukan Outliers Menggunakan Pandas
# Tugas Praktek
"""

import pandas as pd
order_df = pd.read_csv("https://storage.googleapis.com/dqlab-dataset/order.csv")

# Hitung quartile 1
Q1 = order_df[["product_weight_gram"]].quantile(0.25)

# Hitung quartile 3

Q3 = order_df[["product_weight_gram"]].quantile(0.75)
# Hitung inter quartile range dan cetak ke console

IQR = Q3 - Q1
print(IQR)

"""# Rename Kolom Data Frame
# Tugas Praktek
"""

import pandas as pd
order_df = pd.read_csv("https://storage.googleapis.com/dqlab-dataset/order.csv")

# Ganti nama kolom freight_value menjadi shipping_cost
order_df.rename(columns={"freight_value": "shipping_cost"}, inplace=True)
print(order_df)

"""# .groupby menggunakan Pandas
# Tugas Praktek
"""

import pandas as pd
order_df = pd.read_csv("https://storage.googleapis.com/dqlab-dataset/order.csv")

# Hitung rata rata dari price per payment_type
rata_rata = order_df["price"].groupby(order_df["payment_type"]).mean()
print(rata_rata)

"""# Sorting Menggunakan Pandas
# Tugas Praktek
"""

import pandas as pd
order_df = pd.read_csv("https://storage.googleapis.com/dqlab-dataset/order.csv")

# Hitung harga maksimum pembelian customer
sort_harga = order_df.sort_values(by="price", ascending=False)
print(sort_harga)

"""# Mini Project"""

import pandas as pd
import matplotlib.pyplot as plt
order_df = pd.read_csv("https://storage.googleapis.com/dqlab-dataset/order.csv")

# Median price yang dibayar customer dari masing-masing metode pembayaran.
median_price = order_df["price"].groupby(order_df["payment_type"]).median()
print(median_price)

# Ubah freight_value menjadi shipping_cost dan cari shipping_cost
# termahal dari data penjualan tersebut menggunakan sort.
order_df.rename(columns={"freight_value": "shipping_cost"}, inplace=True)
sort_value = order_df.sort_values(by="shipping_cost", ascending=0)
print(sort_value)

# Untuk product_category_name, berapa rata-rata weight produk tersebut
# dan standar deviasi mana yang terkecil dari weight tersebut,
mean_value = order_df["product_weight_gram"].groupby(order_df["product_category_name"]).mean()
print(mean_value.sort_values())
std_value = order_df["product_weight_gram"].groupby(order_df["product_category_name"]).std()
print(std_value.sort_values())

# Buat histogram quantity penjualan dari dataset tersebutuntuk melihat persebaran quantity
# penjualan tersebut dengan bins = 5 dan figsize= (4,5)
order_df[["quantity"]].hist(figsize=(4, 5), bins=5)
plt.show()