# -*- coding: utf-8 -*-
"""Introduction to Data Science with Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15h5WfWSzK5VdiLEr0kKeJPH9D3xgFnPx

# Python “Hello World” & Statement
"""

print("Hello World.")
print("Saya Aksara, baru belajar Python.")

"""# Variables di Python"""

bil1 = 10
Bil_2 = 20
Frasa = "Halo Dunia"
bil1, Bil_2 = 10, 20
salam = "Selamat Pagi"; Penutup = "Salam Sejahtera"

"""# Comments di Python"""

#perintah pada baris ini tidak mempengaruhi program
'''
perintah ini tidak akan dieksekusi oleh Python
dan perintah ini juga tidak akan dieksekusi
perintah ini juga tidak akan dieksekusi
'''
print("jadi # digunakan untuk membuat comment pada Python")

"""# Tugas Praktek"""

text = "Belajar Python di DQLab."
print(list(text))
print(tuple(text))
print(set(text))

"""# Menggunakan Library di Python

"""

import math
import numpy as np
import pandas as pd
import seaborn as sns